// Two-locale chrome strings for the answer-turn UI. unknown/absent -> en.
// The `en` values are verbatim the strings the components shipped with.
type Lang = 'es' | 'en'

const STRINGS: Record<Lang, Record<string, string>> = {
  en: {
    answercheck_prompt: 'does this answer the question?',
    answercheck_yes: 'this answers it',
    answercheck_no: 'not yet',
    answercheck_marked_yes: '✓ marked: this answers it',
    answercheck_saved_pre: 'saved to ',
    answercheck_saved_mid: 'this matters',
    answercheck_saved_post: '. ask anything else when ready.',
    answercheck_marked_no: '↻ marked: not yet',
    answercheck_no_msg: 'where did it break? try a follow-up below or rephrase.',
    you_asked: 'you asked',
    go_deeper: 'go deeper',
    running: 'running…',
    banner_ungrounded_kicker: 'not grounded',
    banner_ungrounded_text:
      'This answer is not anchored to code the tutor actually read, so it may be invented. Either the project does not cover this, or the tutor answered too soon. Re-ask, or point at a specific file, function, or commit.',
    banner_off_target_kicker: 'off target',
    banner_off_target_text:
      'This is grounded in the code, but it answers a different question than you asked. Re-ask to redirect it to what you meant.',
    banner_insufficient_evidence_kicker: 'insufficient evidence',
    banner_insufficient_evidence_text:
      'The tutor looked but the project does not contain enough to answer this confidently. What it would need is named above.',
    banner_partial_kicker: 'partial answer',
    banner_partial_text: 'This answer was interrupted before it finished. It may be incomplete.',
    banner_fallback_kicker: 'no answer',
    banner_fallback_text: 'The tutor could not produce an answer for this question this time.',
    provenance_legacy: 'predates grounding checks — provenance not verified',
    provenance_unjudged: 'the reviewer was unavailable — this answer was not checked for responsiveness',
    provenance_artifacts_uncited: 'the diagrams in this answer cite no read code',
    graph_truncated: 'graph truncated to the strongest connections',
    playground_run: 'run example',
    playground_preparing: 'preparing…',
    playground_ended: 'runtime ended — run again to relaunch',
    playground_evicted: 'paused — another example is running',
    playground_step_through: 'Step through',
    playground_anchored: 'Anchored function',
    playground_run_note: 'Runs your real code once, side effects included.',
    playground_python_limit: 'Steps through your Python; library calls appear as one step.',
    playground_preview_lead: "I'll step through this call:",
    playground_edit_call: 'Edit call',
    playground_cancel: 'Cancel',
    playground_preparing_capturing: 'running once · capturing trace',
    playground_state: 'State',
    playground_next_change: 'next change ◆',
    playground_truncated: 'Stopped at step {n} — trace truncated.',
    playground_truncated_steps: 'Stopped at step {n} — hit the step cap.',
    playground_truncated_time: 'Stopped at step {n} — ran out of time.',
    playground_raised_final: 'Raised — this is the final step.',
    playground_raised_label: 'raised',
    playground_fallback_note: "This function can't be stepped through yet — {reason}. Here's its input and output.",
    playground_runtime_closed: 'Runtime closed',
    playground_runtime_closed_body: 'The sandbox shut down after idle. The captured trace is gone.',
    playground_reopen: 'Reopen',
    playground_evicted_title: 'Evicted',
    playground_evicted_body: 'Another example took this slot. Only one playground runs at a time.',
    playground_bring_back: 'Bring it back',
    playground_spawn_error: 'Spawn error',
    playground_spawn_error_body: "The playground didn't start. Nothing ran — your code wasn't touched.",
    playground_try_again: 'Try again',
    playground_complete_call: "Complete the call's arguments before stepping through.",
  },
  es: {
    answercheck_prompt: '¿esto responde tu pregunta?',
    answercheck_yes: 'esto lo responde',
    answercheck_no: 'todavía no',
    answercheck_marked_yes: '✓ marcado: esto lo responde',
    answercheck_saved_pre: 'guardado en ',
    answercheck_saved_mid: 'esto importa',
    answercheck_saved_post: '. pregunta lo que quieras cuando estés listo.',
    answercheck_marked_no: '↻ marcado: todavía no',
    answercheck_no_msg: '¿dónde se rompió? prueba un seguimiento abajo o reformula.',
    you_asked: 'preguntaste',
    go_deeper: 'más a fondo',
    running: 'corriendo…',
    banner_ungrounded_kicker: 'sin fundamento',
    banner_ungrounded_text:
      'Esta respuesta no está anclada a código que el tutor haya leído de verdad, así que podría estar inventada. O el proyecto no lo cubre, o el tutor respondió demasiado pronto. Vuelve a preguntar, o apunta a un archivo, función o commit específico.',
    banner_off_target_kicker: 'fuera de foco',
    banner_off_target_text:
      'Esto está anclado al código, pero responde una pregunta distinta a la que hiciste. Vuelve a preguntar para redirigirlo a lo que querías decir.',
    banner_insufficient_evidence_kicker: 'evidencia insuficiente',
    banner_insufficient_evidence_text:
      'El tutor buscó, pero el proyecto no contiene lo suficiente para responder esto con confianza. Lo que haría falta está nombrado arriba.',
    banner_partial_kicker: 'respuesta parcial',
    banner_partial_text: 'Esta respuesta se interrumpió antes de terminar. Puede estar incompleta.',
    banner_fallback_kicker: 'sin respuesta',
    banner_fallback_text: 'El tutor no pudo responder esta pregunta esta vez.',
    provenance_legacy: 'anterior a los chequeos de calidad, procedencia sin verificar',
    provenance_unjudged: 'el revisor no estaba disponible: no se chequeó si la respuesta responde lo que preguntaste',
    provenance_artifacts_uncited: 'los diagramas de esta respuesta no citan código leído',
    graph_truncated: 'grafo truncado a las conexiones más fuertes',
    playground_run: 'correr ejemplo',
    playground_preparing: 'preparando…',
    playground_ended: 'el runtime terminó: corre de nuevo para relanzarlo',
    playground_evicted: 'en pausa: hay otro ejemplo corriendo',
    playground_step_through: 'Recorrer',
    playground_anchored: 'Función anclada',
    playground_run_note: 'Corre tu código real una vez, con sus efectos.',
    playground_python_limit: 'Recorre tu Python; las llamadas a librerías son un paso.',
    playground_preview_lead: 'Voy a recorrer esta llamada:',
    playground_edit_call: 'Editar llamada',
    playground_cancel: 'Cancelar',
    playground_preparing_capturing: 'corriendo una vez · capturando la traza',
    playground_state: 'Estado',
    playground_next_change: 'siguiente cambio ◆',
    playground_truncated: 'Detenido en el paso {n} — traza truncada.',
    playground_truncated_steps: 'Detenido en el paso {n} — alcanzó el límite de pasos.',
    playground_truncated_time: 'Detenido en el paso {n} — se agotó el tiempo.',
    playground_raised_final: 'Lanzó — este es el paso final.',
    playground_raised_label: 'lanzó',
    playground_fallback_note: 'Esta función no se puede recorrer paso a paso todavía — {reason}. Aquí está su entrada y salida.',
    playground_runtime_closed: 'Runtime cerrado',
    playground_runtime_closed_body: 'El sandbox se apagó tras estar inactivo. La traza capturada se perdió.',
    playground_reopen: 'Reabrir',
    playground_evicted_title: 'Desalojado',
    playground_evicted_body: 'Otro ejemplo tomó este espacio. Solo corre un playground a la vez.',
    playground_bring_back: 'Traerlo de vuelta',
    playground_spawn_error: 'Error al iniciar',
    playground_spawn_error_body: 'El playground no arrancó. Nada corrió — tu código no se tocó.',
    playground_try_again: 'Reintentar',
    playground_complete_call: 'Completa los argumentos de la llamada antes de recorrer.',
  },
}

export function pickLang(lang?: string | null): Lang {
  return lang === 'es' ? 'es' : 'en'
}

export function t(key: string, lang?: string | null, params?: Record<string, string>): string {
  const l = pickLang(lang)
  const raw = STRINGS[l][key] ?? STRINGS.en[key] ?? key
  if (!params) return raw
  return raw.replace(/\{(\w+)\}/g, (match, k) => (k in params ? params[k] : match))
}
