// scenes.jsx — content for each frame
// Each scene is rendered as a function that returns JSX inside <Cuaderno>.
// Exposed via window so the canvas can pick which one to render.

const FILE_SAMPLES = {
  'src/copyclip/intelligence/analyzer.py': {
    rangeStart: 148,
    lines: [
      { n: 148, t: '' },
      { n: 149, t: '' },
      { n: 150, t: '# ---- module-derivation helpers ------------------------------' },
      { n: 151, t: '' },
      { n: 152, t: 'def _module_from_relpath(rel: str) -> str:' },
      { n: 153, t: '    """Derive the architectural module of a file from its repo-relative path.' },
      { n: 154, t: '' },
      { n: 155, t: '    Returns slash-style ("copyclip/intelligence"), NOT dotted Python. Consumed' },
      { n: 156, t: '    by the architecture graph + cross-language queries, which both need a' },
      { n: 157, t: '    path-shape value. Python imports derive their own dotted form elsewhere.' },
      { n: 158, t: '    """' },
      { n: 159, t: '    parts = [p for p in rel.split("/") if p]' },
      { n: 160, t: '    if len(parts) <= 1:' },
      { n: 161, t: '        return "root"' },
      { n: 162, t: '    if parts[0] in {"src", "lib"} and len(parts) > 2:' },
      { n: 163, t: '        parts = parts[1:]' },
      { n: 164, t: '    if len(parts) == 2:' },
      { n: 165, t: '        return parts[0] if parts[0] in {"api", "utils"} else parts[1]' },
      { n: 166, t: '    return "/".join(parts[:-1])   # ← returns "copyclip/intelligence"' },
      { n: 167, t: '' },
      { n: 168, t: '' },
      { n: 169, t: 'def _files_in_module(mod: str, files: list[Path]) -> list[Path]:' },
      { n: 170, t: '    return [f for f in files if _module_from_relpath(_rel(f)) == mod]' },
    ],
    highlight: [152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166],
    blame: { commit: 'a0dae63', who: 'you', when: '2026-04-12', msg: 'fix(playground): derive dotted Python from path, not symbols.module' },
  },
  'src/copyclip/intelligence/playground.py': {
    rangeStart: 298,
    lines: [
      { n: 298, t: '# Resolve the function reference to a callable.' },
      { n: 299, t: '# symbols.module is slash-format (multi-language); Python imports need dotted.' },
      { n: 300, t: '# Derive locally rather than trusting the DB column.' },
      { n: 301, t: 'def _module_from_file(rel: str) -> str:' },
      { n: 302, t: '    parts = [p for p in rel.replace(".py", "").split("/") if p]' },
      { n: 303, t: '    if parts and parts[0] in {"src", "lib"}:' },
      { n: 304, t: '        parts = parts[1:]' },
      { n: 305, t: '    return ".".join(parts)   # ← dotted: "copyclip.intelligence.analyzer"' },
      { n: 306, t: '' },
      { n: 307, t: '' },
      { n: 308, t: 'def resolve_function_ref(name: str, path: str):' },
      { n: 309, t: '    mod_name = _module_from_file(path)' },
      { n: 310, t: '    module   = importlib.import_module(mod_name)' },
      { n: 311, t: '    return getattr(module, name)' },
    ],
    highlight: [301, 302, 303, 304, 305],
    blame: { commit: 'a0dae63', who: 'you', when: '2026-04-12', msg: 'fix(playground): derive dotted Python from path, not symbols.module' },
  },
  'README.md': {
    rangeStart: 1,
    lines: [
      { n: 1, t: '# CopyClip' },
      { n: 2, t: '' },
      { n: 3, t: '> Personal tool for understanding code the AI wrote for you.' },
      { n: 4, t: '' },
      { n: 5, t: '## What this is' },
      { n: 6, t: '' },
      { n: 7, t: 'CopyClip is a single-developer surface for *recovering* the deliberation' },
      { n: 8, t: 'you delegated to an LLM. It is not a chat sidekick, not a code editor,' },
      { n: 9, t: 'and explicitly not a product (see docs/REJECTED.md).' },
      { n: 10, t: '' },
      { n: 11, t: '## Subsystems' },
      { n: 12, t: '' },
      { n: 13, t: '1. **Analyzer** — parses the repo, builds the symbols graph.' },
      { n: 14, t: '2. **Codebase Map** — interactive 3D atlas of the graph.' },
      { n: 15, t: '3. **Cuaderno** — conversational surface (this page).' },
      { n: 16, t: '' },
    ],
    highlight: [3, 7, 8, 9],
    blame: { commit: 'e6f12c1', who: 'you', when: '2026-05-26', msg: 'docs: name the cuaderno surface; rejected.md commitment' },
  },
};

window.FILE_SAMPLES = FILE_SAMPLES;
