import type { Block, Citation, Frame } from '../../../types/api'
import { CitationChip } from '../CitationChip'
import { t } from '../strings'
import { GraphSubset } from '../widgets/GraphSubset'
import { SequenceDiagram } from '../widgets/SequenceDiagram'
import { CallersTree } from '../widgets/CallersTree'
import { GraphView } from '../widgets/GraphView'
import { PlaygroundWidget } from '../widgets/PlaygroundWidget'

function statusBanner(
  status: NonNullable<Frame['status']>,
  lang?: string | null,
): { kicker: string; text: string } | undefined {
  const map: Partial<Record<NonNullable<Frame['status']>, string>> = {
    ungrounded: 'ungrounded',
    off_target: 'off_target',
    insufficient_evidence: 'insufficient_evidence',
    partial: 'partial',
    fallback: 'fallback',
  }
  const k = map[status]
  if (!k) return undefined
  return { kicker: t(`banner_${k}_kicker`, lang), text: t(`banner_${k}_text`, lang) }
}

type Props = {
  frame: Frame
  onOpenCitation: (c: Citation) => void
  onAsk: (question: string) => void
  language?: string | null
}

export function FrameDynamic({ frame, onOpenCitation, onAsk, language }: Props) {
  const lang = frame.question_language ?? language
  const banner = frame.status ? statusBanner(frame.status, lang) : undefined
  const isLegacy = frame.status === 'legacy'
  // An `answer` sealed before the verdict field existed (pre-Phase-2) is also
  // unverified provenance — distinguish it from a judged answer.
  const preJudge =
    frame.status === 'answer' && (frame.verdict === undefined || frame.verdict === null)
  // A judge-outage answer is sealed `answer` but was never actually checked —
  // the record says `source: unjudged`. Surface that, don't present it as judged.
  const judgeUnavailable =
    frame.status === 'answer' && frame.verdict != null && frame.verdict.source === 'unjudged'
  const showProvenance = isLegacy || preJudge || judgeUnavailable
  const provenanceNotes: string[] = []
  if (showProvenance) {
    provenanceNotes.push(
      judgeUnavailable ? t('provenance_unjudged', lang) : t('provenance_legacy', lang),
    )
  }
  // Wave-2 honesty backbone: a frame whose widgets carry zero citations
  // confesses it — the axis never changes status, it only discloses.
  if (frame.verdict?.artifacts_cited === false) {
    provenanceNotes.push(t('provenance_artifacts_uncited', lang))
  }
  // On a non-answer disposition, the answer's own follow-ups were generated by an
  // answer the system has disavowed — do not invite continuing in that direction.
  const isAnswerish = !frame.status || frame.status === 'answer' || frame.status === 'legacy'
  const blocks = isAnswerish
    ? frame.blocks
    : frame.blocks.filter((b) => b.kind !== 'followups')
  return (
    <>
      <div className="cua-question">
        <span className="label">{t('you_asked', lang)}</span>
        <span className="q">{frame.question}</span>
      </div>
      {banner ? (
        <div className="callout" role="status">
          <div className="kicker">{banner.kicker}</div>
          <p>{banner.text}</p>
        </div>
      ) : null}
      {provenanceNotes.length > 0 ? (
        <div
          style={{
            fontFamily: 'var(--font-ui)',
            fontSize: 11,
            letterSpacing: '0.04em',
            color: 'var(--ink-4)',
            marginBottom: 12,
          }}
        >
          {provenanceNotes.map((n, i) => (
            <div key={i}>{n}</div>
          ))}
        </div>
      ) : null}
      {blocks.map((b, i) => (
        <BlockRender key={i} block={b} onOpenCitation={onOpenCitation} onAsk={onAsk} lang={lang} />
      ))}
    </>
  )
}

function BlockRender({
  block,
  onOpenCitation,
  onAsk,
  lang,
}: {
  block: Block
  onOpenCitation: (c: Citation) => void
  onAsk: (question: string) => void
  lang?: string | null
}) {
  switch (block.kind) {
    case 'lead':
      return <p className="cua-lead">{block.text}</p>
    case 'paragraph':
      return <p className="cua-p">{block.text}</p>
    case 'ordered_list':
      return (
        <ol className="cua-list">
          {block.items.map((item, i) => (
            <li key={i}>
              <div>
                <div className="head">{item.head}</div>
                <div className="desc">{item.desc}</div>
                {item.citation ? (
                  <CitationChip citation={item.citation} block onClick={onOpenCitation} />
                ) : null}
              </div>
            </li>
          ))}
        </ol>
      )
    case 'code_block':
      return (
        <>
          {block.citation ? (
            <CitationChip citation={block.citation} block onClick={onOpenCitation} />
          ) : null}
          <pre className="code">
            {block.code.split('\n').map((l, i) => (
              <span className="ln" key={i}>
                {l || ' '}
                {'\n'}
              </span>
            ))}
          </pre>
        </>
      )
    case 'ascii_block':
      return <pre className="ascii">{block.text}</pre>
    case 'citation':
      return <CitationChip citation={block.citation} block onClick={onOpenCitation} />
    case 'citation_stack':
      return (
        <div className="cite-stack">
          {block.items.map((it, i) => (
            <a key={i} onClick={() => onOpenCitation(it.citation)}>
              <span className="arrow">▸</span>
              <span>
                {it.citation.kind === 'commit'
                  ? `commit ${it.citation.commit}`
                  : `${it.citation.path}${
                      it.citation.line_start
                        ? `:${it.citation.line_start}${
                            it.citation.line_end && it.citation.line_end !== it.citation.line_start
                              ? `-${it.citation.line_end}`
                              : ''
                          }`
                        : ''
                    }`}
              </span>
              {it.note ? (
                <span style={{ color: 'var(--ink-3)' }}>  {it.note}</span>
              ) : null}
            </a>
          ))}
        </div>
      )
    case 'callout':
      return (
        <div className="callout">
          <div className="kicker">{block.kicker}</div>
          <p>{block.text}</p>
          {block.citations
            ? block.citations.map((c, i) => (
                <div key={i} style={{ marginTop: i === 0 ? 8 : 4 }}>
                  <CitationChip citation={c} onClick={onOpenCitation} />
                </div>
              ))
            : null}
        </div>
      )
    case 'widget':
      switch (block.widget.kind) {
        case 'graph_subset':
          return <GraphSubset widget={block.widget} />
        case 'sequence_diagram':
          return <SequenceDiagram widget={block.widget} />
        case 'callers_tree':
          return (
            <CallersTree widget={block.widget} onOpenCitation={onOpenCitation} />
          )
        case 'graph_view':
          return (
            <GraphView widget={block.widget} onOpenCitation={onOpenCitation} lang={lang} />
          )
        case 'playground':
          return (
            <PlaygroundWidget widget={block.widget} onOpenCitation={onOpenCitation} lang={lang} />
          )
      }
      return null
    case 'followups':
      return (
        <div className="followups">
          <div className="cap">{t('go_deeper', lang)}</div>
          <div className="btns">
            {block.items.map((it, i) => (
              <button key={i} className="fu" onClick={() => onAsk(it.question)}>
                <span className="arr">↳</span> {it.label}
              </button>
            ))}
          </div>
        </div>
      )
  }
}
